[package]
name = "Number_word_translate"
version = "0.1.0"
authors = ["trygve <trygve.woldseth@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
